import * as fs from 'fs';
import * as path from 'path';
import { ToolRegistry, schema, stringProp, optionalStringArg, virtualPathDescription } from '../registry';
import { textResult, errorResult, scopeViolationResult, ToolContext } from '../types';
import { NO_ALLOWED_DIRS_MESSAGE } from '../security';
import { LabelEntry } from '../types';
import { checkPathV, decodeInboundPath, describeError, hostToVirtualOrRedact, translateResult } from '../vpath';
import { capLines, MAX_SEARCH_RESULT_BYTES } from '../limits';
import { escapePathField, pathFieldEscapingRules, RESULT_TRAILER_RULE } from '../resultFormat';

const MAX_ENTRIES = 5000;

function entryType(entry: fs.Dirent): string {
  if (entry.isSymbolicLink()) return 'symlink';
  if (entry.isDirectory()) return 'directory';
  if (entry.isFile()) return 'file';
  return 'other';
}

// Issue #31's `escapePathField` used to live here, as a fact about this one
// tool's record. Issue #37 is what happens when a shared property is written
// down in one place: `fs_glob`, `fs_find` and `fs_grep` had the identical
// exposure and did not adopt it. It is in `resultFormat.ts` now, unchanged in
// behaviour for `fs_list`, with the full argument for the scheme (why escape
// rather than skip, why the backslash pass is first and unconditional, why a
// file's own CONTENT is never escaped) in its doc comment there.

/**
 * List one directory's immediate children.
 *
 * `lstat`, never `stat`: fs_list names what physically sits in the directory
 * entry table, not what a symlink among them points at. A symlink is
 * reported as "symlink", with its own mtime and a size of ZERO, so an entry
 * pointing outside the allowed directory is disclosed as a name, a type and
 * a timestamp, with nothing about its target resolved, followed, or
 * measured.
 *
 * The zero is issue #28 and is not cosmetic. This used to print `st.size`
 * for a symlink like any other entry, and for a symlink `st_size` IS THE
 * BYTE LENGTH OF THE TARGET PATH STRING -- so the size column was an exact
 * measurement of a path the client is not allowed to know exists, on the
 * one entry type where every other surface in this server refuses to say
 * anything at all (`fs_read` of that same link is "outside allowed
 * directories"). A `latest -> /Volumes/Backup/2026-08-26-nightly` shape is
 * ordinary in a real tree, and its length confirms or eliminates a guessed
 * host path in a single call; `fs_move` lets a client rename links freely,
 * so links can be enumerated cheaply too. Zero costs nothing to report,
 * because a link's own size is not the size of anything a caller can read:
 * every operation here either refuses or acts on the link itself.
 *
 * The comment this replaces claimed a containment property the code did not
 * have -- "disclosed only as a name and a type", while the size column was
 * disclosing the exact length of the target. Now it is true.
 *
 * There is no recursion here for the same fs_glob/fs_grep-shaped reasoning
 * to apply to: every path this returns is `path.join(dir, entry.name)` for
 * an `entry.name` readdir itself produced, which cannot contain a path
 * separator or `..`, so it cannot name anything outside `dir` no matter what
 * that entry turns out to be.
 */
function listOneDir(dir: string, labels: LabelEntry[]): { lines: string[] } | { error: string } {
  let entries: fs.Dirent[];
  try {
    entries = fs.readdirSync(dir, { withFileTypes: true });
  } catch (err: unknown) {
    return { error: describeError(err, labels) };
  }

  const lines: string[] = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    let size = 0;
    let mtime = '';
    try {
      const st = fs.lstatSync(full);
      // Issue #28: a symlink's st_size is the length of its target path, not
      // the size of anything the caller can read -- see this function's doc.
      // Taken from `st` rather than the readdir Dirent so the answer comes
      // from the same lstat the size itself came from.
      size = st.isSymbolicLink() ? 0 : st.size;
      mtime = st.mtime.toISOString();
    } catch {
      // Vanished between readdir and lstat; still name it, with no stats.
    }
    // Issue #7, outbound: `full` is `path.join(validatedDir, entry.name)`,
    // and this function's own doc comment already argues that can never
    // land outside `dir` (readdir's own entry.name cannot contain a
    // separator or ".."). hostToVirtualOrRedact still runs rather than
    // trusting that argument: the redaction is free, and it is the same
    // "do not emit a path this cannot prove is in scope" rule fs_glob/
    // fs_find/fs_grep apply to output that a symlink genuinely could steer
    // outside their own validated root.
    // escapePathField (issue #31) runs on the virtual path, i.e. last: only
    // the path field can contain a character that carries structure here
    // (type, size and mtime are all generated by this line).
    lines.push(
      `${entryType(entry)}\t${size}\t${mtime}\t${escapePathField(hostToVirtualOrRedact(full, labels))}`
    );
  }
  return { lines };
}

export function registerList(registry: ToolRegistry): void {
  registry.register(
    {
      name: 'fs_list',
      description:
        'List the immediate contents of a directory (non-recursive). One line per entry, ' +
        'tab-separated: "type\\tsize\\tmtime\\tpath". type is one of file, directory, symlink, ' +
        'other. size is bytes, and is always 0 for a symlink (a link\'s own size measures its ' +
        'target path, which is not yours to read). mtime is ISO 8601. ' +
        pathFieldEscapingRules('entry') + ' ' +
        RESULT_TRAILER_RULE + ' ' +
        'Defaults to the allowed directories when path is omitted. ' +
        `Capped at ${MAX_ENTRIES} entries; when it caps, a blank line and a "(showing X of Y ` +
        `entries)" trailer follow the last entry.`,
      inputSchema: schema(
        {
          path: stringProp(virtualPathDescription('Optional; defaults to every directory in this call\'s granted scope.')),
        },
        []
      ),
      // Reads directory entries on the local filesystem only.
      annotations: { readOnlyHint: true, openWorldHint: false },
      category: 'File System',
    },
    (args: Record<string, unknown>, ctx: ToolContext) => {
      const pathArg = optionalStringArg(args, 'path');
      if (typeof pathArg === 'object') return pathArg; // a wrong-typed path is an MCPCallResult refusal

      let dirs: string[];

      if (pathArg && pathArg !== '.') {
        // Issue #7: decode the client's virtual-space address into the host
        // path checkPath (and everything after it) already expects -- see
        // read.ts for the full reasoning. The omitted-path branch below
        // needs no decoding: it falls back to ctx.allowedDirs, which are
        // already host paths.
        const decoded = decodeInboundPath(pathArg, ctx.labels);
        if (typeof decoded !== 'string') return decoded;
        const p = decoded;
        const pathErr = checkPathV(p, ctx.allowedDirs, ctx.labels);
        if (pathErr) return pathErr;
        let st: fs.Stats;
        try {
          st = fs.statSync(p);
        } catch {
          return translateResult(errorResult(`directory not found: ${p}`), [p], ctx.labels);
        }
        if (!st.isDirectory()) {
          return translateResult(errorResult(`not a directory: ${p}`), [p], ctx.labels);
        }
        dirs = [p];
      } else if (ctx.allowedDirs.length > 0) {
        // An absent path resolves to the scope, not to cwd or to everything
        // -- the same reconciliation contract fs_glob/fs_grep already honour
        // (relay's context-schema doc, "What the MCP must do").
        dirs = ctx.allowedDirs.filter((d) => {
          try {
            return fs.statSync(d).isDirectory();
          } catch {
            return false;
          }
        });
        if (dirs.length === 0) return errorResult('none of the allowed directories exist');
      } else {
        return scopeViolationResult(NO_ALLOWED_DIRS_MESSAGE);
      }

      const allLines: string[] = [];
      for (const dir of dirs) {
        const result = listOneDir(dir, ctx.labels);
        if ('error' in result) {
          return translateResult(errorResult(`list error: ${result.error}`), [dir], ctx.labels);
        }
        allLines.push(...result.lines);
      }

      // Issue #19: 5000 entries was a cap on the COUNT and on nothing else,
      // and an entry line carries a name, a type, a size and an mtime -- at
      // PATH_MAX-length names that is over 5 MB, half of relay's frame cap,
      // from a plain directory listing. capLines applies the shared byte
      // budget alongside the entry cap and says which one it hit; the
      // "(showing X of Y entries)" wording is unchanged, because a caller
      // that already understands this tool's cap should not have to learn a
      // second vocabulary for the same statement.
      const capped = capLines(allLines, MAX_ENTRIES);
      if (capped.total === 0) return textResult('(empty)');
      if (!capped.capped) return textResult(capped.text);

      const why =
        capped.reason === 'bytes' ? `, cut at fs_list's ${MAX_SEARCH_RESULT_BYTES}-byte listing limit` : '';
      const result = textResult(
        `${capped.text}\n\n(showing ${capped.shown} of ${capped.total} entries${why})`
      );
      result._meta = { truncated: true };
      return result;
    }
  );
}
